### ISSUE TITLE
pypi upload is broken

### ISSUE THREAD

**Issue by monkeysecurity** [monkeysecurity/iampoliciesgonewild#5]
pypi 1.0.5 works:
https://pypi.python.org/pypi/iampoliciesgonewild/1.0.5

1.0.6 is broken:
https://pypi.python.org/pypi/iampoliciesgonewild/1.0.6

```
>>> from iampoliciesgonewild import expand_policy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../.virtualenvs/blah2/lib/python2.7/site-packages/iampoliciesgonewild/__init__.py", line 26, in <module>
    with open(master_permissions_path) as json_data:
IOError: [Errno 2] No such file or directory: .../.virtualenvs/blah2/lib/python2.7/site-packages/iampoliciesgonewild/master_permissions.json'
```

Also, there's no `.whl` and the readme is missing.

I'm unable to login to pypi right now so I can't delete 1.0.6.

**Comment by monkeysecurity** [comment]
Should be fixed by #6 

1.0.6.2 uploaded to pypi.

(Will resume the 1.0.X numbering scheme for future uploads)
